"""Phase 5.4 baseline schema

Revision ID: 4e729d826d67
Revises: 
Create Date: 2026-09-24 16:42:19.814015
"""
from alembic import op
import sqlalchemy as sa


revision = '4e729d826d67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basis_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('futures_price', sa.Float(), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('basis', sa.Float(), nullable=False),
    sa.Column('futures_provider', sa.String(length=64), nullable=False),
    sa.Column('spot_provider', sa.String(length=64), nullable=False),
    sa.Column('futures_symbol', sa.String(length=32), nullable=False),
    sa.Column('spot_symbol', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basis_observations_timestamp'), 'basis_observations', ['timestamp'], unique=False)
    op.create_table('build_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('base_timeframe', sa.String(length=16), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eligible_total', sa.Integer(), nullable=False),
    sa.Column('built', sa.Integer(), nullable=False),
    sa.Column('skipped_existing', sa.Integer(), nullable=False),
    sa.Column('excluded_roll', sa.Integer(), nullable=False),
    sa.Column('excluded_gaps', sa.Integer(), nullable=False),
    sa.Column('excluded_insufficient_future', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('last_checkpoint_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earliest_state', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_state', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('states_per_second', sa.Float(), nullable=True),
    sa.Column('db_state_count', sa.Integer(), nullable=True),
    sa.Column('counter_state_count', sa.Integer(), nullable=True),
    sa.Column('counter_db_difference', sa.Integer(), nullable=True),
    sa.Column('reconciliation_warning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_jobs_instrument'), 'build_jobs', ['instrument'], unique=False)
    op.create_index(op.f('ix_build_jobs_job_id'), 'build_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_build_jobs_started_at'), 'build_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_build_jobs_status'), 'build_jobs', ['status'], unique=False)
    op.create_table('catchup_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('offline_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_sync_status', sa.String(length=16), nullable=False),
    sa.Column('research_sync_status', sa.String(length=16), nullable=False),
    sa.Column('forward_outcome_status', sa.String(length=16), nullable=False),
    sa.Column('historical_state_status', sa.String(length=16), nullable=False),
    sa.Column('recovered_market_candles', sa.Integer(), nullable=False),
    sa.Column('recovered_spot_observations', sa.Integer(), nullable=False),
    sa.Column('research_items_added', sa.Integer(), nullable=False),
    sa.Column('forward_outcomes_evaluated', sa.Integer(), nullable=False),
    sa.Column('missed_forward_captures', sa.Integer(), nullable=False),
    sa.Column('historical_states_added', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catchup_jobs_job_id'), 'catchup_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_catchup_jobs_started_at'), 'catchup_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_catchup_jobs_status'), 'catchup_jobs', ['status'], unique=False)
    op.create_table('forward_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('observation_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forward_audit_log_event_type'), 'forward_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_forward_audit_log_observation_id'), 'forward_audit_log', ['observation_id'], unique=False)
    op.create_index(op.f('ix_forward_audit_log_timestamp'), 'forward_audit_log', ['timestamp'], unique=False)
    op.create_table('forward_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collector_running', sa.Boolean(), nullable=False),
    sa.Column('evaluator_running', sa.Boolean(), nullable=False),
    sa.Column('last_valid_quote_price', sa.Float(), nullable=True),
    sa.Column('last_valid_quote_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_m15_capture_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_h1_capture_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluation_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_observations', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('uptime_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forward_heartbeats_timestamp'), 'forward_heartbeats', ['timestamp'], unique=False)
    op.create_table('forward_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('live_instrument', sa.String(length=32), nullable=False),
    sa.Column('live_provider', sa.String(length=64), nullable=False),
    sa.Column('live_symbol', sa.String(length=32), nullable=False),
    sa.Column('live_market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('live_price', sa.Float(), nullable=False),
    sa.Column('technical_decision', sa.String(length=16), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('technical_rule_version', sa.String(length=16), nullable=False),
    sa.Column('technical_data_readiness', sa.Float(), nullable=False),
    sa.Column('historical_similarity_run_id', sa.String(length=32), nullable=True),
    sa.Column('historical_analogue_instrument', sa.String(length=32), nullable=True),
    sa.Column('historical_alignment', sa.String(length=32), nullable=True),
    sa.Column('historical_sample_size', sa.Integer(), nullable=True),
    sa.Column('historical_direction_rate', sa.Float(), nullable=True),
    sa.Column('historical_probability_calibrated', sa.Boolean(), nullable=False),
    sa.Column('historical_median_mfe', sa.Float(), nullable=True),
    sa.Column('historical_median_mae', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('similarity_version', sa.String(length=16), nullable=False),
    sa.Column('outcome_version', sa.String(length=16), nullable=False),
    sa.Column('market_regime', sa.String(length=32), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('h1_direction', sa.String(length=32), nullable=True),
    sa.Column('h4_direction', sa.String(length=32), nullable=True),
    sa.Column('d1_direction', sa.String(length=32), nullable=True),
    sa.Column('instrument_consistency', sa.String(length=32), nullable=True),
    sa.Column('capture_timeframe', sa.String(length=16), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_freshness_status', sa.String(length=16), nullable=False),
    sa.Column('observation_status', sa.String(length=32), nullable=False),
    sa.Column('invalid_reason', sa.String(length=64), nullable=True),
    sa.Column('wait_historical_context', sa.String(length=32), nullable=True),
    sa.Column('quote_age_seconds', sa.Float(), nullable=True),
    sa.Column('brain_analysis_age_seconds', sa.Float(), nullable=True),
    sa.Column('similarity_run_age_seconds', sa.Float(), nullable=True),
    sa.Column('similarity_run_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('similarity_run_market_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_instrument', 'capture_timeframe', 'capture_timestamp', 'technical_rule_version', 'feature_version', name='uq_fwd_obs_inst_tf_ts_rule_feat')
    )
    op.create_index(op.f('ix_forward_observations_created_at'), 'forward_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_forward_observations_historical_similarity_run_id'), 'forward_observations', ['historical_similarity_run_id'], unique=False)
    op.create_index(op.f('ix_forward_observations_live_instrument'), 'forward_observations', ['live_instrument'], unique=False)
    op.create_index(op.f('ix_forward_observations_observation_id'), 'forward_observations', ['observation_id'], unique=True)
    op.create_index(op.f('ix_forward_observations_observation_status'), 'forward_observations', ['observation_status'], unique=False)
    op.create_table('forward_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.String(length=32), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('outcome_instrument', sa.String(length=32), nullable=False),
    sa.Column('outcome_provider', sa.String(length=64), nullable=False),
    sa.Column('outcome_source_timeframe', sa.String(length=16), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('future_price', sa.Float(), nullable=True),
    sa.Column('absolute_change', sa.Float(), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('max_up_move', sa.Float(), nullable=True),
    sa.Column('max_down_move', sa.Float(), nullable=True),
    sa.Column('buy_mfe', sa.Float(), nullable=True),
    sa.Column('buy_mae', sa.Float(), nullable=True),
    sa.Column('sell_mfe', sa.Float(), nullable=True),
    sa.Column('sell_mae', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('resolution_sufficient', sa.Boolean(), nullable=True),
    sa.Column('horizon_valid', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_status', sa.String(length=16), nullable=False),
    sa.Column('invalid_reason', sa.String(length=64), nullable=True),
    sa.Column('target_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_future_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_error_seconds', sa.Float(), nullable=True),
    sa.Column('elapsed_wall_time', sa.Float(), nullable=True),
    sa.Column('elapsed_market_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id', 'horizon_minutes', name='uq_fwd_outcome_obs_horizon')
    )
    op.create_index(op.f('ix_forward_outcomes_observation_id'), 'forward_outcomes', ['observation_id'], unique=False)
    op.create_table('historical_feature_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema_fast', sa.Float(), nullable=True),
    sa.Column('ema_slow', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('swing_high', sa.Float(), nullable=True),
    sa.Column('swing_low', sa.Float(), nullable=True),
    sa.Column('support_low', sa.Float(), nullable=True),
    sa.Column('support_high', sa.Float(), nullable=True),
    sa.Column('resistance_low', sa.Float(), nullable=True),
    sa.Column('resistance_high', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('session', sa.String(length=32), nullable=True),
    sa.Column('timeframe_alignment', sa.Float(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_historical_feature_s_i_t')
    )
    op.create_index(op.f('ix_historical_feature_snapshots_interval'), 'historical_feature_snapshots', ['interval'], unique=False)
    op.create_index(op.f('ix_historical_feature_snapshots_symbol'), 'historical_feature_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_feature_snapshots_timestamp'), 'historical_feature_snapshots', ['timestamp'], unique=False)
    op.create_table('historical_market_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_timeframe', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ema_fast', sa.Float(), nullable=True),
    sa.Column('ema_slow', sa.Float(), nullable=True),
    sa.Column('ema_distance_pct', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=True),
    sa.Column('market_regime', sa.String(length=32), nullable=True),
    sa.Column('distance_to_support_atr', sa.Float(), nullable=True),
    sa.Column('distance_to_resistance_atr', sa.Float(), nullable=True),
    sa.Column('swing_structure', sa.String(length=32), nullable=True),
    sa.Column('higher_high', sa.Boolean(), nullable=True),
    sa.Column('higher_low', sa.Boolean(), nullable=True),
    sa.Column('lower_high', sa.Boolean(), nullable=True),
    sa.Column('lower_low', sa.Boolean(), nullable=True),
    sa.Column('volatility_percentile', sa.Float(), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('h1_direction', sa.String(length=32), nullable=True),
    sa.Column('h4_direction', sa.String(length=32), nullable=True),
    sa.Column('d1_direction', sa.String(length=32), nullable=True),
    sa.Column('timeframe_alignment_score', sa.Float(), nullable=True),
    sa.Column('source_quality', sa.String(length=16), nullable=False),
    sa.Column('possible_contract_roll', sa.Boolean(), nullable=False),
    sa.Column('roll_gap_size', sa.Float(), nullable=True),
    sa.Column('roll_detection_reason', sa.String(length=255), nullable=True),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('similarity_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument', 'base_timeframe', 'timestamp', 'feature_version', name='uq_hist_state_inst_tf_ts_fv')
    )
    op.create_index(op.f('ix_historical_market_states_base_timeframe'), 'historical_market_states', ['base_timeframe'], unique=False)
    op.create_index(op.f('ix_historical_market_states_feature_version'), 'historical_market_states', ['feature_version'], unique=False)
    op.create_index(op.f('ix_historical_market_states_instrument'), 'historical_market_states', ['instrument'], unique=False)
    op.create_index(op.f('ix_historical_market_states_possible_contract_roll'), 'historical_market_states', ['possible_contract_roll'], unique=False)
    op.create_index(op.f('ix_historical_market_states_timestamp'), 'historical_market_states', ['timestamp'], unique=False)
    op.create_table('historical_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('future_price', sa.Float(), nullable=True),
    sa.Column('absolute_change', sa.Float(), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('max_up_move', sa.Float(), nullable=True),
    sa.Column('max_down_move', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_valid', sa.Boolean(), nullable=False),
    sa.Column('actual_elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=64), nullable=True),
    sa.Column('possible_contract_roll', sa.Boolean(), nullable=False),
    sa.Column('roll_gap_size', sa.Float(), nullable=True),
    sa.Column('excluded_from_learning', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('outcome_source_timeframe', sa.String(length=16), nullable=True),
    sa.Column('outcome_source_provider', sa.String(length=64), nullable=True),
    sa.Column('outcome_source_instrument', sa.String(length=32), nullable=True),
    sa.Column('resolution_sufficient', sa.Boolean(), nullable=True),
    sa.Column('outcome_version', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'horizon_minutes', name='uq_hist_outcome_state_h')
    )
    op.create_index(op.f('ix_historical_outcomes_excluded_from_learning'), 'historical_outcomes', ['excluded_from_learning'], unique=False)
    op.create_index(op.f('ix_historical_outcomes_horizon_minutes'), 'historical_outcomes', ['horizon_minutes'], unique=False)
    op.create_index(op.f('ix_historical_outcomes_horizon_valid'), 'historical_outcomes', ['horizon_valid'], unique=False)
    op.create_index(op.f('ix_historical_outcomes_possible_contract_roll'), 'historical_outcomes', ['possible_contract_roll'], unique=False)
    op.create_index(op.f('ix_historical_outcomes_state_id'), 'historical_outcomes', ['state_id'], unique=False)
    op.create_table('historical_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('earliest_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candles', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('provider_symbol', sa.String(length=32), nullable=False),
    sa.Column('derivation', sa.String(length=16), nullable=False),
    sa.Column('source_timeframe', sa.String(length=16), nullable=False),
    sa.Column('target_timeframe', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', 'interval', name='uq_historical_sync_p_s_i')
    )
    op.create_index(op.f('ix_historical_sync_state_instrument'), 'historical_sync_state', ['instrument'], unique=False)
    op.create_index(op.f('ix_historical_sync_state_interval'), 'historical_sync_state', ['interval'], unique=False)
    op.create_index(op.f('ix_historical_sync_state_last_sync_at'), 'historical_sync_state', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_historical_sync_state_provider'), 'historical_sync_state', ['provider'], unique=False)
    op.create_index(op.f('ix_historical_sync_state_symbol'), 'historical_sync_state', ['symbol'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('derivation', sa.String(length=16), nullable=False),
    sa.Column('provider_symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('source_timeframe', sa.String(length=16), nullable=False),
    sa.Column('target_timeframe', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_candle_symbol_interval_time')
    )
    op.create_index(op.f('ix_market_candles_derivation'), 'market_candles', ['derivation'], unique=False)
    op.create_index(op.f('ix_market_candles_instrument'), 'market_candles', ['instrument'], unique=False)
    op.create_index(op.f('ix_market_candles_interval'), 'market_candles', ['interval'], unique=False)
    op.create_index(op.f('ix_market_candles_is_historical'), 'market_candles', ['is_historical'], unique=False)
    op.create_index(op.f('ix_market_candles_symbol'), 'market_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_candles_timestamp'), 'market_candles', ['timestamp'], unique=False)
    op.create_table('market_ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market_timestamp', name='uq_tick_symbol_time')
    )
    op.create_index(op.f('ix_market_ticks_market_timestamp'), 'market_ticks', ['market_timestamp'], unique=False)
    op.create_index(op.f('ix_market_ticks_received_at'), 'market_ticks', ['received_at'], unique=False)
    op.create_index(op.f('ix_market_ticks_symbol'), 'market_ticks', ['symbol'], unique=False)
    op.create_table('missed_forward_captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_timeframe', sa.String(length=16), nullable=False),
    sa.Column('expected_capture_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offline_reason', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missed_forward_captures_expected_capture_timestamp'), 'missed_forward_captures', ['expected_capture_timestamp'], unique=False)
    op.create_table('prediction_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('future_price', sa.Float(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=False),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', 'horizon_minutes', name='uq_prediction_horizon')
    )
    op.create_index(op.f('ix_prediction_outcomes_prediction_id'), 'prediction_outcomes', ['prediction_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('against_json', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('brain_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_decision'), 'predictions', ['decision'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('research_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('source_country', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    op.create_index(op.f('ix_research_news_discovered_at'), 'research_news', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_research_news_domain'), 'research_news', ['domain'], unique=False)
    op.create_index(op.f('ix_research_news_seen_at'), 'research_news', ['seen_at'], unique=False)
    op.create_table('similarity_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_market_price', sa.Float(), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('analogue_instrument', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('similarity_version', sa.String(length=16), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('technical_decision', sa.String(length=16), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('raw_neighbor_count', sa.Integer(), nullable=False),
    sa.Column('independent_neighbor_count', sa.Integer(), nullable=False),
    sa.Column('minimum_spacing_seconds', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('highest_similarity', sa.Float(), nullable=True),
    sa.Column('median_selected_similarity', sa.Float(), nullable=True),
    sa.Column('lowest_selected_similarity', sa.Float(), nullable=True),
    sa.Column('similarity_25th_percentile', sa.Float(), nullable=True),
    sa.Column('similarity_75th_percentile', sa.Float(), nullable=True),
    sa.Column('top_match_ids', sa.Text(), nullable=False),
    sa.Column('statistics_json', sa.Text(), nullable=False),
    sa.Column('historical_alignment', sa.String(length=32), nullable=True),
    sa.Column('feature_history_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_history_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_history_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_history_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_history_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_history_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_days', sa.Float(), nullable=True),
    sa.Column('probability_calibrated', sa.Boolean(), nullable=False),
    sa.Column('outcome_version', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_runs_analogue_instrument'), 'similarity_runs', ['analogue_instrument'], unique=False)
    op.create_index(op.f('ix_similarity_runs_created_at'), 'similarity_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_similarity_runs_horizon_minutes'), 'similarity_runs', ['horizon_minutes'], unique=False)
    op.create_index(op.f('ix_similarity_runs_instrument'), 'similarity_runs', ['instrument'], unique=False)
    op.create_index(op.f('ix_similarity_runs_run_id'), 'similarity_runs', ['run_id'], unique=True)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('last_successful_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component', name='uq_sync_state_component')
    )
    op.create_index(op.f('ix_system_sync_state_component'), 'system_sync_state', ['component'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_sync_state_component'), table_name='system_sync_state')
    op.drop_table('system_sync_state')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_similarity_runs_run_id'), table_name='similarity_runs')
    op.drop_index(op.f('ix_similarity_runs_instrument'), table_name='similarity_runs')
    op.drop_index(op.f('ix_similarity_runs_horizon_minutes'), table_name='similarity_runs')
    op.drop_index(op.f('ix_similarity_runs_created_at'), table_name='similarity_runs')
    op.drop_index(op.f('ix_similarity_runs_analogue_instrument'), table_name='similarity_runs')
    op.drop_table('similarity_runs')
    op.drop_index(op.f('ix_research_news_seen_at'), table_name='research_news')
    op.drop_index(op.f('ix_research_news_domain'), table_name='research_news')
    op.drop_index(op.f('ix_research_news_discovered_at'), table_name='research_news')
    op.drop_table('research_news')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_decision'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_outcomes_prediction_id'), table_name='prediction_outcomes')
    op.drop_table('prediction_outcomes')
    op.drop_index(op.f('ix_missed_forward_captures_expected_capture_timestamp'), table_name='missed_forward_captures')
    op.drop_table('missed_forward_captures')
    op.drop_index(op.f('ix_market_ticks_symbol'), table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_received_at'), table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_market_timestamp'), table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_index(op.f('ix_market_candles_timestamp'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_symbol'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_is_historical'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_interval'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_instrument'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_derivation'), table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_historical_sync_state_symbol'), table_name='historical_sync_state')
    op.drop_index(op.f('ix_historical_sync_state_provider'), table_name='historical_sync_state')
    op.drop_index(op.f('ix_historical_sync_state_last_sync_at'), table_name='historical_sync_state')
    op.drop_index(op.f('ix_historical_sync_state_interval'), table_name='historical_sync_state')
    op.drop_index(op.f('ix_historical_sync_state_instrument'), table_name='historical_sync_state')
    op.drop_table('historical_sync_state')
    op.drop_index(op.f('ix_historical_outcomes_state_id'), table_name='historical_outcomes')
    op.drop_index(op.f('ix_historical_outcomes_possible_contract_roll'), table_name='historical_outcomes')
    op.drop_index(op.f('ix_historical_outcomes_horizon_valid'), table_name='historical_outcomes')
    op.drop_index(op.f('ix_historical_outcomes_horizon_minutes'), table_name='historical_outcomes')
    op.drop_index(op.f('ix_historical_outcomes_excluded_from_learning'), table_name='historical_outcomes')
    op.drop_table('historical_outcomes')
    op.drop_index(op.f('ix_historical_market_states_timestamp'), table_name='historical_market_states')
    op.drop_index(op.f('ix_historical_market_states_possible_contract_roll'), table_name='historical_market_states')
    op.drop_index(op.f('ix_historical_market_states_instrument'), table_name='historical_market_states')
    op.drop_index(op.f('ix_historical_market_states_feature_version'), table_name='historical_market_states')
    op.drop_index(op.f('ix_historical_market_states_base_timeframe'), table_name='historical_market_states')
    op.drop_table('historical_market_states')
    op.drop_index(op.f('ix_historical_feature_snapshots_timestamp'), table_name='historical_feature_snapshots')
    op.drop_index(op.f('ix_historical_feature_snapshots_symbol'), table_name='historical_feature_snapshots')
    op.drop_index(op.f('ix_historical_feature_snapshots_interval'), table_name='historical_feature_snapshots')
    op.drop_table('historical_feature_snapshots')
    op.drop_index(op.f('ix_forward_outcomes_observation_id'), table_name='forward_outcomes')
    op.drop_table('forward_outcomes')
    op.drop_index(op.f('ix_forward_observations_observation_status'), table_name='forward_observations')
    op.drop_index(op.f('ix_forward_observations_observation_id'), table_name='forward_observations')
    op.drop_index(op.f('ix_forward_observations_live_instrument'), table_name='forward_observations')
    op.drop_index(op.f('ix_forward_observations_historical_similarity_run_id'), table_name='forward_observations')
    op.drop_index(op.f('ix_forward_observations_created_at'), table_name='forward_observations')
    op.drop_table('forward_observations')
    op.drop_index(op.f('ix_forward_heartbeats_timestamp'), table_name='forward_heartbeats')
    op.drop_table('forward_heartbeats')
    op.drop_index(op.f('ix_forward_audit_log_timestamp'), table_name='forward_audit_log')
    op.drop_index(op.f('ix_forward_audit_log_observation_id'), table_name='forward_audit_log')
    op.drop_index(op.f('ix_forward_audit_log_event_type'), table_name='forward_audit_log')
    op.drop_table('forward_audit_log')
    op.drop_index(op.f('ix_catchup_jobs_status'), table_name='catchup_jobs')
    op.drop_index(op.f('ix_catchup_jobs_started_at'), table_name='catchup_jobs')
    op.drop_index(op.f('ix_catchup_jobs_job_id'), table_name='catchup_jobs')
    op.drop_table('catchup_jobs')
    op.drop_index(op.f('ix_build_jobs_status'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_started_at'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_job_id'), table_name='build_jobs')
    op.drop_index(op.f('ix_build_jobs_instrument'), table_name='build_jobs')
    op.drop_table('build_jobs')
    op.drop_index(op.f('ix_basis_observations_timestamp'), table_name='basis_observations')
    op.drop_table('basis_observations')
    # ### end Alembic commands ###
